name: WDIO + Mocha

on:
  workflow_dispatch:
    inputs:
      node:
        description: "Node.js version"
        default: "18"
        required: true
        type: string
  push:
    branches: [ main, master ]
    paths:
      - 'WebdriverIO/WDIO-mocha/**'
      - '.github/workflows/wdio-mocha.yml'
  pull_request:
    paths:
      - 'WebdriverIO/WDIO-mocha/**'
      - '.github/workflows/wdio-mocha.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ github.event.inputs.node || '20' }}

      - name: Install dependencies
        run: npm --prefix "WebdriverIO/WDIO-mocha" ci || npm --prefix "WebdriverIO/WDIO-mocha" install

      - name: Run WDIO tests (Mocha)
        run: npx --prefix "WebdriverIO/WDIO-mocha" wdio run "WebdriverIO/WDIO-mocha/wdio.conf.ts"

      - name: Upload allure-results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wdio-mocha-allure-results
          path: "WebdriverIO/WDIO-mocha/allure-results"
          if-no-files-found: ignore

      - name: Generate Allure report
        if: always()
        run: npx --no-install --prefix "WebdriverIO/WDIO-mocha" allure generate --clean "WebdriverIO/WDIO-mocha/allure-results" -o "WebdriverIO/WDIO-mocha/allure-report"

      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wdio-mocha-allure-report
          path: "WebdriverIO/WDIO-mocha/allure-report"
          if-no-files-found: ignore


